apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: autotune-pxoo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: autotune-pxoo
    app.kubernetes.io/part-of: autotune
  name: autotune-pxoo
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: autotune-pxoo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: autotune-pxoo
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:Rnb0C-autotune-pxoo
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
